name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Run hassfest validation # https://github.com/home-assistant/actions
        uses: home-assistant/actions/hassfest@master

  hacs: # https://hacs.xyz/docs/publish/action/
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation # https://github.com/hacs/action
        uses: hacs/action@main
        with:
          category: integration
          # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
          ignore: brands